[package]
name = "omni-shelf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = "1.4.8"
pretty_env_logger = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3.2"